language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql
  - DB=mysql
  - DB=pgsql
  - DB=agnostic
  - DB=sqlite
  
before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction

matrix:
  include:
    - php: 5.5
      env: DB=mysql MARIADB=5.5
      addons:
        mariadb: 5.5
    - php: 5.6
      env: DB=mysql MARIADB=5.5
      addons:
        mariadb: 5.5
    - php: 7.0
      env: DB=mysql MARIADB=5.5
      addons:
        mariadb: 5.5

    - php: 5.5
      env: DB=mysql MARIADB=10.0
      addons:
        mariadb: 10.0
    - php: 5.6
      env: DB=mysql MARIADB=10.0
      addons:
        mariadb: 10.0
    - php: 7.0
      env: DB=mysql MARIADB=10.0
      addons:
        mariadb: 10.0

    - php: 5.5
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: 10.1
    - php: 5.6
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: 10.1

    - php: 5.5
      env: DB=pgsql POSTGRES=9.1
      addons:
        postgresql: 9.1
    - php: 5.6
      env: DB=pgsql POSTGRES=9.1
      addons:
        postgresql: 9.1
    - php: 7.0
      env: DB=pgsql POSTGRES=9.1
      addons:
        postgresql: 9.1

    - php: 5.5
      env: DB=pgsql POSTGRES=9.2
      addons:
        postgresql: 9.2
    - php: 5.6
      env: DB=pgsql POSTGRES=9.2
      addons:
        postgresql: 9.2
    - php: 7.0
      env: DB=pgsql POSTGRES=9.2
      addons:
        postgresql: 9.2

    - php: 5.5
      env: DB=pgsql POSTGRES=9.3
      addons:
        postgresql: 9.3
    - php: 5.6
      env: DB=pgsql POSTGRES=9.3
      addons:
        postgresql: 9.3
    - php: 7.0
      env: DB=pgsql POSTGRES=9.3
      addons:
        postgresql: 9.3

    - php: 5.5
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 5.6
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 7.0
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4

  allow_failures:
    - php: 
      - nightly
      - hhvm

  fast_finish: true
  
# cache vendors
cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_script:
  - composer install
  - phpenv rehash
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

script: php mageekguy.atoum.phar

notifications:
    email:
        - vigiloproject@gmail.com
