language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  
before_script:
  - composer install
before_script: wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar

env:
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql
  - DB=mysql
  - DB=pgsql

script: php mageekguy.atoum.phar
